navsat_transform:
  frequency: 10
  delay: 2.0
  magnetic_declination_radians: 0.0241437213
  yaw_offset: 0
  zero_altitude: true
  broadcast_utm_transform: true
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: false
